stock ReplaceEmoticionsToText(string[250])
{
	strreplace(string, "xd", "*śmieje się*");
	strreplace(string, "xD", "*śmieje się*");
	strreplace(string, "XD", "*śmieje się*");
	strreplace(string, "Xd", "*śmieje się*");
	strreplace(string, ":D", "*śmieje się*");
	strreplace(string, ";D", "*śmieje się*");
	strreplace(string, ":d", "*śmieje się*");
	strreplace(string, ";d", "*śmieje się*");
	strreplace(string, ":P", "*wystawia jezyk*");
	strreplace(string, ":p", "*wystawia jezyk*");
	strreplace(string, ";P", "*wystawia jezyk*");
	strreplace(string, ";p", "*wystawia jezyk*");
	strreplace(string, "Lol", "*wybucha śmiechem*");
	strreplace(string, "lul", "*wybucha śmiechem*");
	strreplace(string, "Lul", "*wybucha śmiechem*");
	strreplace(string, "LoL", "*wybucha śmiechem*");
	strreplace(string, "LuL", "*wybucha śmiechem*");
	strreplace(string, "lol", "*wybucha śmiechem*");
	strreplace(string, "LOL", "*wybucha śmiechem*");
	strreplace(string, ":)", "*uśmiecha się*");
	strreplace(string, ";)", "*puszcza oczko*");
	strreplace(string, ":(", "*robi smutną minę*");
	strreplace(string, ";(", "*robi smutną minę*");
	strreplace(string, ":c", "*robi smutną minę*");
	strreplace(string, ";c", "*robi smutną minę*");
	strreplace(string, ":C", "*robi smutną minę*");
	strreplace(string, ";C", "*robi smutną minę*");
	strreplace(string, ";/", "*robi grymas*");
	strreplace(string, ":/", "*robi grymas*");
	strreplace(string, ";>", "*mruży oczy*");
	strreplace(string, ":>", "*mruży oczy*");
	strreplace(string, ";<", "*robi dziubek*");
	strreplace(string, ":<", "*robi dziubek*");
	strreplace(string, ";*", "*wysyła buziaka*");
	strreplace(string, ":*", "*wysyła buziaka*");
	strreplace(string, ";o", "*robi zdziwioną minę*");
	strreplace(string, ":o", "*robi zdziwioną minę*");
	strreplace(string, ";O", "*robi zdziwioną minę*");
	strreplace(string, ":O", "*robi zdziwioną minę*");
	strreplace(string, "^_^", "*robi śmieszną minę*");
	strreplace(string, "^^", "*robi śmieszną minę*");
	strreplace(string, "<3", "*pokazuje serce z rąk*");
	strreplace(string, ";3", "*robi słodką minkę*");
	strreplace(string, ":3", "*robi słodką minkę*");
	strreplace(string, ";x", "*zakrywa buzie ręką*");
	strreplace(string, ":x", "*zakrywa buzie ręką*");
	strreplace(string, ";X", "*zakrywa buzie ręką*");
	strreplace(string, ":X", "*zakrywa buzie ręką*");
	strreplace(string, ";v", "*robi dziubek*");
	strreplace(string, ":v", "*robi dziubek*");
	strreplace(string, ":]", "*robi szeroki uśmiech*");
	strreplace(string, ";]", "*robi szeroki uśmiech*");
	strreplace(string, ":[", "*robi smutną minę*");
	strreplace(string, ";[", "*robi smutną minę*");
	strreplace(string, "wtf", "*robi zdziwioną minę*");
	strreplace(string, "WTF", "*robi zdziwioną minę*");
	strreplace(string, "wTF", "*robi zdziwioną minę*");
	strreplace(string, "wTf", "*robi zdziwioną minę*");
	strreplace(string, "WTf", "*robi zdziwioną minę*");
	strreplace(string, "WtF", "*robi zdziwioną minę*");
	strreplace(string, "wtF", "*robi zdziwioną minę*");
	strreplace(string, "omg", "*robi zdziwioną minę*");
	strreplace(string, "OMG", "*robi zdziwioną minę*");
	strreplace(string, "Omg", "*robi zdziwioną minę*");
	strreplace(string, "OMg", "*robi zdziwioną minę*");
	strreplace(string, "oMg", "*robi zdziwioną minę*");
	strreplace(string, "OMg", "*robi zdziwioną minę*");
	return 1;
}
