stock ReplaceEmoticionsToText(string[250])
{
	strreplace(string, "xd", "*œmieje siê*");
	strreplace(string, "xD", "*œmieje siê*");
	strreplace(string, "XD", "*œmieje siê*");
	strreplace(string, "Xd", "*œmieje siê*");
	strreplace(string, ":D", "*œmieje siê*");
	strreplace(string, ";D", "*œmieje siê*");
	strreplace(string, ":d", "*œmieje siê*");
	strreplace(string, ";d", "*œmieje siê*");
	strreplace(string, ":P", "*wystawia jezyk*");
	strreplace(string, ":p", "*wystawia jezyk*");
	strreplace(string, ";P", "*wystawia jezyk*");
	strreplace(string, ";p", "*wystawia jezyk*");
	strreplace(string, "Lol", "*wybucha œmiechem*");
	strreplace(string, "lul", "*wybucha œmiechem*");
	strreplace(string, "Lul", "*wybucha œmiechem*");
	strreplace(string, "LoL", "*wybucha œmiechem*");
	strreplace(string, "LuL", "*wybucha œmiechem*");
	strreplace(string, "lol", "*wybucha œmiechem*");
	strreplace(string, "LOL", "*wybucha œmiechem*");
	strreplace(string, ":)", "*uœmiecha siê*");
	strreplace(string, ";)", "*puszcza oczko*");
	strreplace(string, ":(", "*robi smutn¹ minê*");
	strreplace(string, ";(", "*robi smutn¹ minê*");
	strreplace(string, ":c", "*robi smutn¹ minê*");
	strreplace(string, ";c", "*robi smutn¹ minê*");
	strreplace(string, ":C", "*robi smutn¹ minê*");
	strreplace(string, ";C", "*robi smutn¹ minê*");
	strreplace(string, ";/", "*robi grymas*");
	strreplace(string, ":/", "*robi grymas*");
	strreplace(string, ";>", "*mru¿y oczy*");
	strreplace(string, ":>", "*mru¿y oczy*");
	strreplace(string, ";<", "*robi dziubek*");
	strreplace(string, ":<", "*robi dziubek*");
	strreplace(string, ";*", "*wysy³a buziaka*");
	strreplace(string, ":*", "*wysy³a buziaka*");
	strreplace(string, ";o", "*robi zdziwion¹ minê*");
	strreplace(string, ":o", "*robi zdziwion¹ minê*");
	strreplace(string, ";O", "*robi zdziwion¹ minê*");
	strreplace(string, ":O", "*robi zdziwion¹ minê*");
	strreplace(string, "^_^", "*robi œmieszn¹ minê*");
	strreplace(string, "^^", "*robi œmieszn¹ minê*");
	strreplace(string, "<3", "*pokazuje serce z r¹k*");
	strreplace(string, ";3", "*robi s³odk¹ minkê*");
	strreplace(string, ":3", "*robi s³odk¹ minkê*");
	strreplace(string, ";x", "*zakrywa buzie rêk¹*");
	strreplace(string, ":x", "*zakrywa buzie rêk¹*");
	strreplace(string, ";X", "*zakrywa buzie rêk¹*");
	strreplace(string, ":X", "*zakrywa buzie rêk¹*");
	strreplace(string, ";v", "*robi dziubek*");
	strreplace(string, ":v", "*robi dziubek*");
	strreplace(string, ":]", "*robi szeroki uœmiech*");
	strreplace(string, ";]", "*robi szeroki uœmiech*");
	strreplace(string, ":[", "*robi smutn¹ minê*");
	strreplace(string, ";[", "*robi smutn¹ minê*");
	strreplace(string, "wtf", "*robi zdziwion¹ minê*");
	strreplace(string, "WTF", "*robi zdziwion¹ minê*");
	strreplace(string, "wTF", "*robi zdziwion¹ minê*");
	strreplace(string, "wTf", "*robi zdziwion¹ minê*");
	strreplace(string, "WTf", "*robi zdziwion¹ minê*");
	strreplace(string, "WtF", "*robi zdziwion¹ minê*");
	strreplace(string, "wtF", "*robi zdziwion¹ minê*");
	strreplace(string, "omg", "*robi zdziwion¹ minê*");
	strreplace(string, "OMG", "*robi zdziwion¹ minê*");
	strreplace(string, "Omg", "*robi zdziwion¹ minê*");
	strreplace(string, "OMg", "*robi zdziwion¹ minê*");
	strreplace(string, "oMg", "*robi zdziwion¹ minê*");
	strreplace(string, "OMg", "*robi zdziwion¹ minê*");
	return 1;
}
